# Generated by Django 4.2.4 on 2023-08-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holder", models.CharField(max_length=255)),
                ("number", models.TextField()),
                ("cvv", models.CharField(blank=True, max_length=4)),
                ("exp_date", models.DateField()),
                ("brand", models.CharField(max_length=500)),
            ],
        ),
    ]
