# Generated by Django 4.2.4 on 2023-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="exp_date",
            field=models.CharField(max_length=10),
        ),
    ]
