# Generated by Django 4.2.4 on 2023-08-20 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_creditcard_cvv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="cvv",
            field=models.IntegerField(
                blank=True, validators=[django.core.validators.MaxValueValidator(4)]
            ),
        ),
    ]
