# Generated by Django 4.2.4 on 2023-08-20 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_alter_creditcard_cvv"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
