# Generated by Django 4.2.4 on 2023-08-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_creditcard_created_at_creditcard_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
