version: '3'
services:
  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev_pas_9898
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=credit_card_register
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - '5432'

volumes:
  postgres_data: