version: '3'
services:
  database:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev_pas_9898
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=credit_card_register
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - '5432'

  server:
    image: credit-card-register:latest
    build: .
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - type: bind
        source: .
        target: /server/
    depends_on:
      - database

volumes:
  postgres_data:

networks:
  default:
    name: register_net